/**
 * Quick Panel Agent Handler
 *
 * Background service that bridges Quick Panel (content script) with the native-server Agent.
 * Handles message routing, SSE streaming, and lifecycle management for AI chat requests.
 *
 * Architecture:
 * - Quick Panel sends QUICK_PANEL_SEND_TO_AI via chrome.runtime.sendMessage
 * - This handler subscribes to SSE first, then fires POST /act
 * - Incoming RealtimeEvents are filtered by requestId and forwarded to the originating tab
 * - Keepalive is explicitly managed to prevent MV3 Service Worker suspension during streaming
 *
 * @see https://developer.chrome.com/docs/extensions/mv3/service_workers/
 */

import type {
  AgentActRequest,
  AgentCliPreference,
  AgentMessage,
  RealtimeEvent,
} from 'chrome-mcp-shared';
import { NativeMessageType } from 'chrome-mcp-shared';

import { NATIVE_HOST, STORAGE_KEYS } from '@/common/constants';
import {
  BACKGROUND_MESSAGE_TYPES,
  TOOL_MESSAGE_TYPES,
  type QuickPanelAIEventMessage,
  type QuickPanelActivateSessionMessage,
  type QuickPanelActivateSessionResponse,
  type QuickPanelCancelAIMessage,
  type QuickPanelCancelAIResponse,
  type QuickPanelDeleteSessionMessage,
  type QuickPanelDeleteSessionResponse,
  type QuickPanelGetBrandingMessage,
  type QuickPanelGetBrandingResponse,
  type QuickPanelSetSessionEngineMessage,
  type QuickPanelSetSessionEngineResponse,
  type QuickPanelOpenSessionMessage,
  type QuickPanelOpenSessionResponse,
  type QuickPanelPersistSessionMessage,
  type QuickPanelPersistSessionResponse,
  type QuickPanelSendToAIMessage,
  type QuickPanelSendToAIResponse,
} from '@/common/message-types';
import { acquireKeepalive } from '../keepalive-manager';
import { openAgentChatSidepanel } from '../utils/sidepanel';

// ============================================================
// Constants
// ============================================================

const LOG_PREFIX = '[QuickPanelAgent]';
const KEEPALIVE_TAG = 'quick-panel-ai';

/** Storage key for AgentChat selected session ID (owned by sidepanel composables) */
const STORAGE_KEY_SELECTED_PROJECT = 'agent-selected-project-id';

const STORAGE_KEY_QP_PERSIST_ENABLED = 'quick-panel-persist-enabled';

/** Number of messages to return to the launcher on expand. */
const QUICK_PANEL_RECENT_MESSAGES_LIMIT = 12;

/** Fallback engine when no session exists yet. */
const QUICK_PANEL_DEFAULT_ENGINE_NAME = 'claude';

/** Timeout for initial SSE connection establishment */
const SSE_CONNECT_TIMEOUT_MS = 3000;

/** Safety timeout for entire request lifecycle (15 minutes) */
const REQUEST_TIMEOUT_MS = 15 * 60 * 1000;

/** Flag indicating SSE connection was successful */
const SSE_CONNECTED = Symbol('SSE_CONNECTED');

/** Flag indicating SSE connection timed out but we should continue */
const SSE_TIMEOUT = Symbol('SSE_TIMEOUT');

// ============================================================
// Types
// ============================================================

/**
 * Represents an active streaming request from Quick Panel.
 *
 * Background maintains this state to:
 * 1. Route SSE events to the correct tab
 * 2. Manage keepalive lifecycle
 * 3. Handle cancellation and cleanup
 */
interface ActiveRequest {
  readonly requestId: string;
  readonly sessionId: string;
  readonly projectId: string;
  readonly persistence: 'ephemeral' | 'persisted';
  readonly dbSessionId?: string;
  readonly cliPreference?: string;
  readonly instruction: string;
  readonly tabId: number;
  readonly windowId?: number;
  readonly frameId?: number;
  readonly port: number;
  readonly createdAt: number;
  readonly abortController: AbortController;
  readonly releaseKeepalive: () => void;
  readonly timeoutId: ReturnType<typeof setTimeout>;
}

// ============================================================
// State
// ============================================================

/** Active streaming requests indexed by requestId */
const activeRequests = new Map<string, ActiveRequest>();

/** Initialization flag to prevent duplicate listeners */
let initialized = false;

/** Sidepanel presence tracked via a long-lived port from sidepanel UI. */
const sidepanelPresenceByTabId = new Map<number, { connectedAt: number }>();

/**
 * Per-Quick-Panel-session engine selection.
 *
 * - Keys are per-page Quick Panel session ids generated by the content script.
 * - Persisted DB sessions store their engineName in the DB; this map is for ephemeral sessions only.
 */
const quickSessionEngineBySessionId = new Map<string, AgentCliPreference>();

// ============================================================
// Utility Functions
// ============================================================

function normalizeString(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function isValidCliPreference(value: unknown): value is AgentCliPreference {
  return (
    value === 'openclaw' ||
    value === 'claude' ||
    value === 'codex' ||
    value === 'cursor' ||
    value === 'qwen' ||
    value === 'glm'
  );
}

function getQuickSessionEngine(sessionIdRaw: string): AgentCliPreference {
  const sessionId = normalizeString(sessionIdRaw).trim();
  if (!sessionId) return QUICK_PANEL_DEFAULT_ENGINE_NAME;
  return quickSessionEngineBySessionId.get(sessionId) || QUICK_PANEL_DEFAULT_ENGINE_NAME;
}

function initQuickSessionEngine(
  sessionIdRaw: string,
  options?: { forceNew?: boolean },
): AgentCliPreference {
  const sessionId = normalizeString(sessionIdRaw).trim();
  if (!sessionId) return QUICK_PANEL_DEFAULT_ENGINE_NAME;

  if (options?.forceNew) {
    quickSessionEngineBySessionId.set(sessionId, QUICK_PANEL_DEFAULT_ENGINE_NAME);
    return QUICK_PANEL_DEFAULT_ENGINE_NAME;
  }

  const existing = quickSessionEngineBySessionId.get(sessionId);
  if (existing) return existing;

  quickSessionEngineBySessionId.set(sessionId, QUICK_PANEL_DEFAULT_ENGINE_NAME);
  return QUICK_PANEL_DEFAULT_ENGINE_NAME;
}

function normalizePort(value: unknown): number | null {
  const num =
    typeof value === 'number' ? value : typeof value === 'string' ? Number(value) : Number.NaN;

  if (!Number.isFinite(num)) return null;

  const port = Math.floor(num);
  if (port <= 0 || port > 65535) return null;

  return port;
}

function normalizeBool(value: unknown): boolean {
  if (value === true) return true;
  if (value === false) return false;
  if (typeof value === 'string') {
    const v = value.trim().toLowerCase();
    if (v === 'true' || v === '1' || v === 'yes' || v === 'on') return true;
    if (v === 'false' || v === '0' || v === 'no' || v === 'off') return false;
  }
  return false;
}

function createRequestId(): string {
  // Prefer crypto.randomUUID for proper UUID format
  try {
    const id = crypto?.randomUUID?.();
    if (id) return id;
  } catch {
    // Fallback for environments without crypto.randomUUID
  }
  return `req_${Date.now()}_${Math.random().toString(16).slice(2)}`;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function isTerminalStatus(status: string): boolean {
  return status === 'completed' || status === 'error' || status === 'cancelled';
}

// ============================================================
// Event Factories
// ============================================================

function createErrorEvent(sessionId: string, requestId: string, error: string): RealtimeEvent {
  return {
    type: 'error',
    error: error || 'Unknown error',
    data: { sessionId, requestId },
  };
}

function createCancelledStatusEvent(
  sessionId: string,
  requestId: string,
  message?: string,
): RealtimeEvent {
  return {
    type: 'status',
    data: {
      sessionId,
      status: 'cancelled',
      requestId,
      message: message || 'Cancelled by user',
    },
  };
}

// ============================================================
// Event Forwarding
// ============================================================

/**
 * Forward a RealtimeEvent to the Quick Panel in the originating tab.
 * Handles receiver unavailability gracefully by cleaning up the request.
 */
function forwardEventToQuickPanel(request: ActiveRequest, event: RealtimeEvent): void {
  const message: QuickPanelAIEventMessage = {
    action: TOOL_MESSAGE_TYPES.QUICK_PANEL_AI_EVENT,
    requestId: request.requestId,
    sessionId: request.sessionId,
    event,
  };

  const sendOptions =
    typeof request.frameId === 'number' ? { frameId: request.frameId } : undefined;

  const sendPromise = sendOptions
    ? chrome.tabs.sendMessage(request.tabId, message, sendOptions)
    : chrome.tabs.sendMessage(request.tabId, message);

  sendPromise.catch((err) => {
    const msg = err instanceof Error ? err.message : String(err);

    // Detect receiver unavailability (tab closed, navigated, Quick Panel closed)
    const receiverGone =
      msg.includes('Receiving end does not exist') ||
      msg.includes('No tab with id') ||
      msg.includes('The message port closed');

    if (receiverGone) {
      cleanupRequest(request.requestId, 'receiver_unavailable');
    }
  });
}

// ============================================================
// Request Lifecycle Management
// ============================================================

/**
 * Clean up an active request and release all associated resources.
 * Idempotent - safe to call multiple times.
 */
function cleanupRequest(requestId: string, reason: string): void {
  const request = activeRequests.get(requestId);
  if (!request) return;

  activeRequests.delete(requestId);

  // Clear timeout
  try {
    clearTimeout(request.timeoutId);
  } catch {
    // Ignore
  }

  // Abort SSE connection
  try {
    request.abortController.abort();
  } catch {
    // Ignore
  }

  // Release keepalive
  try {
    request.releaseKeepalive();
  } catch {
    // Ignore
  }

  console.debug(`${LOG_PREFIX} Cleaned up request ${requestId} (${reason})`);
}

// ============================================================
// Session Validation
// ============================================================

/**
 * Validate that the selected session exists on the native server.
 * Returns false if the session is invalid or server is unreachable.
 */
async function validateSession(port: number, sessionId: string): Promise<boolean> {
  const url = `http://127.0.0.1:${port}/agent/sessions/${encodeURIComponent(sessionId)}`;
  try {
    const response = await fetch(url);
    return response.ok;
  } catch {
    return false;
  }
}

async function fetchJson<T>(url: string, init?: RequestInit): Promise<{ ok: boolean; data?: T }> {
  try {
    const response = await fetch(url, init);
    if (!response.ok) return { ok: false };
    const data = (await response.json().catch(() => null)) as T | null;
    if (!data) return { ok: true, data: data as T };
    return { ok: true, data };
  } catch {
    return { ok: false };
  }
}

async function fetchSessionInfo(
  port: number,
  sessionId: string,
): Promise<{ id: string; name?: string; engineName?: string } | null> {
  const url = `http://127.0.0.1:${port}/agent/sessions/${encodeURIComponent(sessionId)}`;
  const result = await fetchJson<any>(url);
  if (!result.ok) return null;
  const session = result.data?.session;
  if (!session?.id) return null;
  return {
    id: String(session.id),
    name: typeof session.name === 'string' ? session.name : undefined,
    engineName: typeof session.engineName === 'string' ? session.engineName : undefined,
  };
}

async function fetchRecentSessionMessages(
  port: number,
  sessionId: string,
  limit: number,
): Promise<AgentMessage[]> {
  const safeLimit = Math.max(0, Math.min(50, Math.floor(limit)));
  if (safeLimit <= 0) return [];

  const url = `http://127.0.0.1:${port}/agent/sessions/${encodeURIComponent(sessionId)}/history?limit=${safeLimit}&offset=0`;
  const result = await fetchJson<any>(url);
  if (!result.ok) return [];
  const messages = Array.isArray(result.data?.messages) ? result.data.messages : [];
  return messages as AgentMessage[];
}

async function listProjects(port: number): Promise<Array<{ id: string }>> {
  const url = `http://127.0.0.1:${port}/agent/projects`;
  const result = await fetchJson<any>(url);
  if (!result.ok) return [];
  const projects = Array.isArray(result.data?.projects) ? result.data.projects : [];
  return projects
    .map((p: any) => ({ id: typeof p?.id === 'string' ? p.id : '' }))
    .filter((p: { id: string }) => !!p.id);
}

async function createSessionForProject(params: {
  port: number;
  projectId: string;
  engineName: string;
  name: string;
  id?: string;
}): Promise<{ id: string; name?: string; engineName?: string } | null> {
  const url = `http://127.0.0.1:${params.port}/agent/projects/${encodeURIComponent(params.projectId)}/sessions`;
  const result = await fetchJson<any>(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      id: typeof params.id === 'string' ? params.id : undefined,
      engineName: params.engineName,
      name: params.name,
    }),
  });

  if (!result.ok) return null;
  const session = result.data?.session;
  if (!session?.id) return null;
  return {
    id: String(session.id),
    name: typeof session.name === 'string' ? session.name : undefined,
    engineName: typeof session.engineName === 'string' ? session.engineName : undefined,
  };
}

// ============================================================
// SSE Event Filtering
// ============================================================

/**
 * Determine if a RealtimeEvent should be forwarded for a specific requestId.
 *
 * Events without requestId (connected, heartbeat) are session-level signals
 * and are not forwarded to avoid confusion with request-specific events.
 */
function shouldForwardEvent(event: RealtimeEvent, requestId: string): boolean {
  switch (event.type) {
    case 'message':
      return event.data?.requestId === requestId;
    case 'status':
      return event.data?.requestId === requestId;
    case 'usage':
      return event.data?.requestId === requestId;
    case 'error':
      return event.data?.requestId === requestId;
    case 'connected':
    case 'heartbeat':
      // Session-level signals, not request-scoped
      return false;
    default:
      return false;
  }
}

// ============================================================
// SSE Subscription
// ============================================================

interface SseSubscription {
  /**
   * Resolves with true when SSE connection is established.
   * Resolves with false if connection failed (request was cleaned up).
   */
  ready: Promise<boolean>;
  /** Resolves when SSE stream ends (normally or due to error/abort) */
  done: Promise<void>;
}

/**
 * Create an SSE subscription for the request's session.
 *
 * The subscription:
 * 1. Connects to the session's /stream endpoint
 * 2. Filters events by requestId
 * 3. Forwards matching events to Quick Panel
 * 4. Triggers cleanup on terminal status
 *
 * @returns SseSubscription with ready promise that resolves to:
 *   - true: SSE connected successfully
 *   - false: SSE failed (request was cleaned up, don't send /act)
 */
function createSseSubscription(request: ActiveRequest): SseSubscription {
  // Track whether ready has been resolved
  let readySettled = false;
  let readyResolve: (connected: boolean) => void;

  const ready = new Promise<boolean>((resolve) => {
    readyResolve = resolve;
  });

  // Helper to resolve ready exactly once
  const settleReady = (connected: boolean): void => {
    if (readySettled) return;
    readySettled = true;
    readyResolve(connected);
  };

  const done = (async () => {
    const sseUrl = `http://127.0.0.1:${request.port}/agent/chat/${encodeURIComponent(request.sessionId)}/stream`;

    try {
      const response = await fetch(sseUrl, {
        method: 'GET',
        headers: { Accept: 'text/event-stream' },
        signal: request.abortController.signal,
      });

      if (!response.ok || !response.body) {
        throw new Error(`SSE stream unavailable (HTTP ${response.status})`);
      }

      // Signal that SSE is connected successfully
      settleReady(true);

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      // Read and parse SSE stream
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() ?? '';

        for (const line of lines) {
          if (!line.startsWith('data:')) continue;
          const raw = line.slice(5).trim();
          if (!raw) continue;

          try {
            const event = JSON.parse(raw) as RealtimeEvent;

            // Filter by requestId to prevent cross-request leakage
            if (!shouldForwardEvent(event, request.requestId)) {
              continue;
            }

            forwardEventToQuickPanel(request, event);

            // Cleanup on terminal status
            if (event.type === 'status' && event.data?.requestId === request.requestId) {
              if (isTerminalStatus(event.data.status)) {
                cleanupRequest(request.requestId, `terminal_status:${event.data.status}`);
                return;
              }
            }
          } catch {
            // Ignore parse errors (best-effort stream processing)
          }
        }
      }
    } catch (err) {
      // AbortError is intentional (cancellation or cleanup)
      if (err instanceof Error && err.name === 'AbortError') {
        // Signal not connected if aborted before connecting
        settleReady(false);
        return;
      }

      // Surface error to UI and cleanup if request is still active
      if (activeRequests.has(request.requestId)) {
        const msg = err instanceof Error ? err.message : String(err);
        forwardEventToQuickPanel(
          request,
          createErrorEvent(request.sessionId, request.requestId, msg),
        );
        cleanupRequest(request.requestId, 'sse_error');
      }

      // Signal failed connection
      settleReady(false);
    }
  })();

  return { ready, done };
}

// ============================================================
// Agent API
// ============================================================

/**
 * Send the act request to native-server.
 * The server will emit events via SSE which are already being subscribed.
 *
 * @param request - Active request context
 * @throws Error if request was cancelled/aborted or HTTP request fails
 */
async function postActRequest(request: ActiveRequest): Promise<void> {
  // Check if request was cancelled before sending
  if (request.abortController.signal.aborted) {
    throw new Error('Request was cancelled');
  }

  const url = `http://127.0.0.1:${request.port}/agent/chat/${encodeURIComponent(request.sessionId)}/act`;

  const payload: AgentActRequest = {
    instruction: request.instruction,
    persistence: request.persistence,
    // Ensures project/workspace is available even for ephemeral requests.
    // When dbSessionId is present, server can derive projectId from session.
    projectId: request.dbSessionId ? undefined : request.projectId,
    // Load session-level config when available (engine, model, options, project binding).
    dbSessionId: request.dbSessionId,
    // Choose engine for ephemeral requests (and as a fallback when session config isn't available).
    // IMPORTANT: when dbSessionId is present, server validates cliPreference matches session.engineName.
    // Quick Panel's selected engine may differ from this session, so omit to avoid false mismatches.
    cliPreference: request.dbSessionId ? undefined : (request.cliPreference as any),
    // Enables SSE-first flow and requestId filtering on session-scoped streams
    requestId: request.requestId,
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
    signal: request.abortController.signal,
  });

  if (!response.ok) {
    const text = await response.text().catch(() => '');
    throw new Error(text || `HTTP ${response.status}`);
  }
}

/**
 * Cancel an active request on the native-server.
 */
async function cancelRequestOnServer(
  port: number,
  sessionId: string,
  requestId: string,
): Promise<void> {
  const url = `http://127.0.0.1:${port}/agent/chat/${encodeURIComponent(sessionId)}/cancel/${encodeURIComponent(requestId)}`;
  try {
    await fetch(url, { method: 'DELETE' });
  } catch {
    // Best-effort: cancellation might still succeed if request already ended
  }
}

// ============================================================
// Request Orchestration
// ============================================================

/**
 * Check if the request is still active and not cancelled.
 * Used as a guard before each async operation to handle race conditions.
 */
function isRequestStillActive(request: ActiveRequest): boolean {
  return activeRequests.has(request.requestId) && !request.abortController.signal.aborted;
}

/**
 * Main orchestration function for starting a Quick Panel AI request.
 *
 * Flow:
 * 1. Ensure native server is running
 * 2. Validate session exists
 * 3. Open sidepanel (best-effort)
 * 4. Start SSE subscription (wait for connection)
 * 5. Fire act request
 * 6. Let SSE handle event forwarding and cleanup
 *
 * @remarks
 * Guards are placed after each async operation to handle cancellation races.
 */
async function startRequest(request: ActiveRequest): Promise<void> {
  try {
    // Best-effort: ensure native server is running
    await chrome.runtime.sendMessage({ type: NativeMessageType.ENSURE_NATIVE }).catch(() => null);

    // Guard: check if cancelled during ENSURE_NATIVE
    if (!isRequestStillActive(request)) return;

    // Start SSE subscription BEFORE sending act request to avoid missing early events
    const sse = createSseSubscription(request);

    // Wait for SSE connection with timeout
    // The race returns either:
    // - boolean from sse.ready (true=connected, false=failed)
    // - undefined from timeout (treat as "proceed with caution")
    const sseResult = await Promise.race([
      sse.ready,
      sleep(SSE_CONNECT_TIMEOUT_MS).then(() => SSE_TIMEOUT),
    ]);

    // Guard: check if cancelled during SSE connection
    if (!isRequestStillActive(request)) return;

    // If SSE explicitly failed (returned false), don't send /act
    // The SSE subscription already cleaned up and sent error to UI
    if (sseResult === false) {
      console.debug(`${LOG_PREFIX} SSE failed for ${request.requestId}, not sending /act`);
      return;
    }

    // If SSE timed out, log warning but continue (degraded experience)
    if (sseResult === SSE_TIMEOUT) {
      console.warn(
        `${LOG_PREFIX} SSE connection timed out for ${request.requestId}, proceeding anyway`,
      );
    }

    // Fire the act request
    await postActRequest(request);

    // SSE subscription continues running and will handle cleanup on terminal status
    void sse.done;
  } catch (err) {
    // Abort errors are expected during cancellation
    if (err instanceof Error && err.name === 'AbortError') {
      return;
    }

    // Request may have been cleaned up already
    if (!activeRequests.has(request.requestId)) return;

    const msg = err instanceof Error ? err.message : String(err);
    console.error(`${LOG_PREFIX} startRequest failed:`, {
      requestId: request.requestId,
      sessionId: request.sessionId,
      persistence: request.persistence,
      dbSessionId: request.dbSessionId,
      error: msg,
    });
    forwardEventToQuickPanel(request, createErrorEvent(request.sessionId, request.requestId, msg));
    cleanupRequest(request.requestId, 'start_failed');
  }
}

// ============================================================
// Message Handlers
// ============================================================

/**
 * Handle QUICK_PANEL_SEND_TO_AI message.
 * Creates a new streaming request and starts the orchestration flow.
 */
async function handleSendToAI(
  message: QuickPanelSendToAIMessage,
  sender: chrome.runtime.MessageSender,
): Promise<QuickPanelSendToAIResponse> {
  const tabId = sender?.tab?.id;
  const windowId = sender?.tab?.windowId;
  const frameId = typeof sender?.frameId === 'number' ? sender.frameId : undefined;

  if (typeof tabId !== 'number') {
    return { success: false, error: 'Quick Panel request must originate from a tab.' };
  }

  const clientSessionId = normalizeString(message?.payload?.sessionId).trim();
  if (!clientSessionId) {
    return { success: false, error: 'sessionId is required' };
  }
  const isQuickSession = message?.payload?.isQuickSession !== false;

  const instruction = normalizeString(message?.payload?.instruction).trim();
  if (!instruction) {
    return { success: false, error: 'instruction is required' };
  }

  // Read server port and selected project/session from storage (sidepanel-owned).
  const stored = await chrome.storage.local.get([
    STORAGE_KEYS.NATIVE_SERVER_PORT,
    STORAGE_KEY_SELECTED_PROJECT,
    STORAGE_KEY_QP_PERSIST_ENABLED,
  ]);

  const port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;
  const selectedProjectId = normalizeString(stored?.[STORAGE_KEY_SELECTED_PROJECT]).trim();
  const persistEnabled = normalizeBool(stored?.[STORAGE_KEY_QP_PERSIST_ENABLED]);

  if (!selectedProjectId) {
    openAgentChatSidepanel(tabId, windowId).catch(() => {});
    return {
      success: false,
      error:
        'No Agent project selected. Please open AgentChat and select/create a project, then try again.',
    };
  }

  const engineName = isQuickSession
    ? initQuickSessionEngine(clientSessionId)
    : QUICK_PANEL_DEFAULT_ENGINE_NAME;

  let effectiveSessionId = clientSessionId;
  let sessionExists = await validateSession(port, effectiveSessionId);
  if (!isQuickSession && !sessionExists) {
    return { success: false, error: 'Session not found' };
  }

  // Persisted mode: ensure DB session exists for this quick session id.
  // For non-quick sessions, persistence is always on and sessions must already exist.
  const shouldPersist = !isQuickSession || persistEnabled;
  if (isQuickSession && shouldPersist && !sessionExists) {
    // Try materializing from ephemeral server-side state first (captures claude resume state).
    const persistUrl = `http://127.0.0.1:${port}/agent/ephemeral-sessions/${encodeURIComponent(effectiveSessionId)}/persist`;
    const materialize = await fetchJson<any>(persistUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messages: [] }),
    });

    if (materialize.ok) {
      const persistedSessionId = normalizeString(materialize.data?.session?.id).trim();
      if (persistedSessionId) {
        effectiveSessionId = persistedSessionId;
      }
      sessionExists = true;
    } else {
      const created = await createSessionForProject({
        port,
        projectId: selectedProjectId,
        engineName,
        name: `Quick Chat (${engineName})`,
        id: effectiveSessionId,
      });
      if (created?.id) {
        effectiveSessionId = created.id;
        sessionExists = true;
      } else {
        sessionExists = false;
      }
    }
  }

  if (isQuickSession && shouldPersist && !sessionExists) {
    return { success: false, error: 'Failed to create persisted Quick Chat session.' };
  }

  const persistence: 'ephemeral' | 'persisted' = shouldPersist ? 'persisted' : 'ephemeral';
  const dbSessionId = shouldPersist && sessionExists ? effectiveSessionId : undefined;

  // Create request state
  const requestId = createRequestId();
  const releaseKeepalive = acquireKeepalive(KEEPALIVE_TAG);
  const abortController = new AbortController();

  // Safety timeout to prevent infinite streaming
  const timeoutId = setTimeout(() => {
    const activeRequest = activeRequests.get(requestId);
    if (!activeRequest) return;

    forwardEventToQuickPanel(
      activeRequest,
      createErrorEvent(
        activeRequest.sessionId,
        activeRequest.requestId,
        'Quick Panel stream timed out. Please continue in AgentChat sidepanel.',
      ),
    );
    cleanupRequest(requestId, 'timeout');
  }, REQUEST_TIMEOUT_MS);

  const request: ActiveRequest = {
    requestId,
    sessionId: effectiveSessionId,
    projectId: selectedProjectId,
    persistence,
    dbSessionId,
    cliPreference: engineName,
    instruction,
    tabId,
    windowId: typeof windowId === 'number' ? windowId : undefined,
    frameId,
    port,
    createdAt: Date.now(),
    abortController,
    releaseKeepalive,
    timeoutId,
  };

  activeRequests.set(requestId, request);

  // Start the request asynchronously (don't await)
  void startRequest(request);

  return { success: true, requestId, sessionId: effectiveSessionId };
}

/**
 * Handle QUICK_PANEL_ACTIVATE_SESSION message.
 * Ensures Quick Panel has enough context to run:
 * - selected project exists
 * - (optional) create a persisted DB session if persistence is enabled
 *
 * IMPORTANT: When persistence is disabled, this must NOT create DB sessions.
 */
async function handleActivateSession(
  message: QuickPanelActivateSessionMessage,
  sender: chrome.runtime.MessageSender,
): Promise<QuickPanelActivateSessionResponse> {
  const tabId = sender?.tab?.id;
  const windowId = sender?.tab?.windowId;

  if (typeof tabId !== 'number') {
    return { success: false, error: 'Quick Panel request must originate from a tab.' };
  }

  const clientSessionId = normalizeString(message?.payload?.sessionId).trim();
  if (!clientSessionId) return { success: false, error: 'sessionId is required' };
  const forceNew = message?.payload?.forceNew === true;

  const stored = await chrome.storage.local.get([
    STORAGE_KEYS.NATIVE_SERVER_PORT,
    STORAGE_KEY_SELECTED_PROJECT,
  ]);

  const port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;
  const selectedProjectId = normalizeString(stored?.[STORAGE_KEY_SELECTED_PROJECT]).trim();

  if (!selectedProjectId) {
    openAgentChatSidepanel(tabId, typeof windowId === 'number' ? windowId : undefined).catch(
      () => {},
    );
    return {
      success: false,
      error: 'No Agent project selected. Please open AgentChat and select/create a project.',
    };
  }

  // IMPORTANT: do NOT create DB sessions here.
  // Persisted mode materialization happens on first send (or explicit "Persist" action) so users can
  // still change engine before the session has started.
  const effectiveSessionId = clientSessionId;

  // Prefer DB engine if this session already exists; otherwise use ephemeral per-session engine.
  const exists = await validateSession(port, effectiveSessionId);
  let engineName: string;
  let recentMessages: AgentMessage[] = [];

  if (exists) {
    const info = await fetchSessionInfo(port, effectiveSessionId);
    engineName = normalizeString(info?.engineName).trim() || QUICK_PANEL_DEFAULT_ENGINE_NAME;
    try {
      recentMessages = await fetchRecentSessionMessages(
        port,
        effectiveSessionId,
        QUICK_PANEL_RECENT_MESSAGES_LIMIT,
      );
    } catch {
      recentMessages = [];
    }
  } else {
    engineName = initQuickSessionEngine(effectiveSessionId, { forceNew });
  }

  const brandIconUrl = engineName ? await resolveEngineIconUrl(engineName) : '';

  return {
    success: true,
    sessionId: effectiveSessionId,
    sessionName: 'Quick Chat',
    reused: true,
    engineName,
    engineDisplayName: toEngineDisplayName(engineName),
    brandIconUrl,
    recentMessages,
  };
}

/**
 * Handle QUICK_PANEL_OPEN_SESSION message.
 * Selects an explicit session by ID and returns recent messages for launcher rendering.
 */
async function handleOpenSession(
  message: QuickPanelOpenSessionMessage,
): Promise<QuickPanelOpenSessionResponse> {
  const sessionId = normalizeString(message?.payload?.sessionId).trim();
  if (!sessionId) {
    return { success: false, error: 'sessionId is required' };
  }

  const stored = await chrome.storage.local.get([STORAGE_KEYS.NATIVE_SERVER_PORT]);
  const port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;

  const sessionInfo = await fetchSessionInfo(port, sessionId);
  if (!sessionInfo?.id) {
    return { success: false, error: 'Session not found' };
  }

  const recentMessages = await fetchRecentSessionMessages(
    port,
    sessionInfo.id,
    QUICK_PANEL_RECENT_MESSAGES_LIMIT,
  );

  const engineName = normalizeString(sessionInfo.engineName).trim();
  const brandIconUrl = engineName ? await resolveEngineIconUrl(engineName) : '';

  return {
    success: true,
    sessionId: sessionInfo.id,
    sessionName: sessionInfo.name || 'Session',
    engineName,
    engineDisplayName: toEngineDisplayName(engineName),
    brandIconUrl,
    recentMessages,
  };
}

/**
 * Handle QUICK_PANEL_DELETE_SESSION message.
 * Deletes a session from native-server and clears local selection when applicable.
 */
async function handleDeleteSession(
  message: QuickPanelDeleteSessionMessage,
): Promise<QuickPanelDeleteSessionResponse> {
  const sessionId = normalizeString(message?.payload?.sessionId).trim();
  if (!sessionId) return { success: false, error: 'sessionId is required' };

  const stored = await chrome.storage.local.get([STORAGE_KEYS.NATIVE_SERVER_PORT]);

  const port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;

  try {
    const url = `http://127.0.0.1:${port}/agent/sessions/${encodeURIComponent(sessionId)}`;
    const resp = await fetch(url, { method: 'DELETE' });
    if (!resp.ok && resp.status !== 404) {
      const text = await resp.text().catch(() => '');
      return { success: false, error: text || `HTTP ${resp.status}` };
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { success: false, error: msg || 'Failed to delete session' };
  }

  return { success: true };
}

/**
 * Handle QUICK_PANEL_PERSIST_SESSION message.
 * Materializes an ephemeral Quick Panel session into a persisted DB session and backfills transcript.
 */
async function handlePersistSession(
  message: QuickPanelPersistSessionMessage,
): Promise<QuickPanelPersistSessionResponse> {
  const sessionId = normalizeString(message?.payload?.sessionId).trim();
  if (!sessionId) return { success: false, error: 'sessionId is required' };

  const messages = Array.isArray(message?.payload?.messages) ? message.payload.messages : [];
  const name = normalizeString(message?.payload?.name).trim();

  const stored = await chrome.storage.local.get([
    STORAGE_KEYS.NATIVE_SERVER_PORT,
    STORAGE_KEY_SELECTED_PROJECT,
  ]);
  const port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;
  const selectedProjectId = normalizeString(stored?.[STORAGE_KEY_SELECTED_PROJECT]).trim();
  const engineName = getQuickSessionEngine(sessionId);

  try {
    const url = `http://127.0.0.1:${port}/agent/ephemeral-sessions/${encodeURIComponent(sessionId)}/persist`;
    const resp = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: name || undefined,
        messages,
        projectId: selectedProjectId || undefined,
        engineName,
      }),
    });

    if (!resp.ok) {
      const text = await resp.text().catch(() => '');
      return { success: false, error: text || `HTTP ${resp.status}` };
    }

    return { success: true, sessionId };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { success: false, error: msg || 'Failed to persist session' };
  }
}

/**
 * Handle QUICK_PANEL_CANCEL_AI message.
 * Cancels an active request both locally and on the server.
 */
async function handleCancelAI(
  message: QuickPanelCancelAIMessage,
  sender: chrome.runtime.MessageSender,
): Promise<QuickPanelCancelAIResponse> {
  const tabId = sender?.tab?.id;
  const frameId = typeof sender?.frameId === 'number' ? sender.frameId : undefined;

  if (typeof tabId !== 'number') {
    return { success: false, error: 'Cancel request must originate from a tab.' };
  }

  const requestId = normalizeString(message?.payload?.requestId).trim();
  const fallbackSessionId = normalizeString(message?.payload?.sessionId).trim();

  if (!requestId) {
    return { success: false, error: 'requestId is required' };
  }

  const activeRequest = activeRequests.get(requestId);
  const sessionId = activeRequest?.sessionId || fallbackSessionId;

  if (!sessionId) {
    return {
      success: false,
      error: 'Unknown sessionId for this request. Please cancel from AgentChat sidepanel.',
    };
  }

  // Abort SSE immediately for responsive UX
  if (activeRequest) {
    try {
      activeRequest.abortController.abort();
    } catch {
      // Ignore
    }
  }

  // Determine port
  let port = activeRequest?.port;
  if (!port) {
    const stored = await chrome.storage.local.get([STORAGE_KEYS.NATIVE_SERVER_PORT]);
    port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;
  }

  // Cancel on server (async, don't await)
  void cancelRequestOnServer(port, sessionId, requestId);

  // Send synthetic cancelled status to UI
  const cancelledEvent = createCancelledStatusEvent(sessionId, requestId);
  const eventMessage: QuickPanelAIEventMessage = {
    action: TOOL_MESSAGE_TYPES.QUICK_PANEL_AI_EVENT,
    requestId,
    sessionId,
    event: cancelledEvent,
  };

  const sendOptions = typeof frameId === 'number' ? { frameId } : undefined;
  const sendPromise = sendOptions
    ? chrome.tabs.sendMessage(tabId, eventMessage, sendOptions)
    : chrome.tabs.sendMessage(tabId, eventMessage);

  sendPromise
    .catch(() => {})
    .finally(() => {
      cleanupRequest(requestId, 'cancelled_by_user');
    });

  return { success: true };
}

/**
 * Handle QUICK_PANEL_OPEN_SIDEPANEL message.
 * Toggles the AgentChat sidepanel for the current tab.
 */
async function handleOpenSidepanel(
  message: unknown,
  sender: chrome.runtime.MessageSender,
): Promise<{ success: boolean; error?: string }> {
  const payload = (message as any)?.payload as
    | { tabId?: unknown; windowId?: unknown }
    | null
    | undefined;
  const payloadTabId = payload?.tabId;
  const payloadWindowId = payload?.windowId;

  const tabId = sender?.tab?.id ?? (typeof payloadTabId === 'number' ? payloadTabId : undefined);
  const windowId =
    sender?.tab?.windowId ?? (typeof payloadWindowId === 'number' ? payloadWindowId : undefined);

  if (typeof tabId !== 'number') {
    return { success: false, error: 'Quick Panel request must originate from a tab.' };
  }

  const sidePanel = chrome.sidePanel as any;

  // IMPORTANT: sidePanel.open is user-gesture sensitive on some Chrome versions.
  // Do not `await` before attempting to open; otherwise open may silently fail.
  const isOpen = sidepanelPresenceByTabId.has(tabId);

  if (isOpen) {
    // Close by disabling for this tab (Chrome has no explicit "close" API).
    try {
      if (sidePanel?.setOptions) {
        void sidePanel.setOptions({ tabId, enabled: false });
      }
    } catch {
      // ignore
    }
    sidepanelPresenceByTabId.delete(tabId);
    return { success: true };
  }

  // Open path: setOptions (fire-and-forget) then open synchronously.
  // `setOptions` is async, but Chrome may apply enabling/path eagerly; do not await.
  try {
    if (sidePanel?.setOptions) {
      const path = `sidepanel.html?tab=agent-chat&tabId=${encodeURIComponent(String(tabId))}`;
      void sidePanel.setOptions({ tabId, path, enabled: true });
    }
  } catch {
    // ignore
  }

  // Best-effort "sync open" (same as context menu handler).
  if (sidePanel?.open) {
    try {
      sidePanel.open({ tabId });
    } catch {
      if (typeof windowId === 'number') {
        try {
          sidePanel.open({ windowId });
        } catch {
          // ignore
        }
      }
    }
  }

  // Also run the async setup (setOptions + deep-link options)
  void openAgentChatSidepanel(tabId, windowId);
  return { success: true };
}

/** Resolve engine display name (matches sidepanel branding). */
function toEngineDisplayName(engineName: string): string {
  const name = engineName.trim();
  switch (name) {
    case 'openclaw':
      return 'OpenClaw';
    case 'claude':
      return 'Claude Code';
    case 'codex':
      return 'Codex';
    case 'cursor':
      return 'Cursor';
    case 'qwen':
      return 'Qwen';
    case 'glm':
      return 'GLM';
    default:
      return name || 'Agent';
  }
}

function getEngineIconUrl(engineName: string): string {
  const normalized = engineName.trim();
  const path =
    normalized === 'openclaw'
      ? 'engine-icons/openclaw.svg'
      : normalized === 'claude'
        ? 'engine-icons/claude.png'
        : normalized === 'codex'
          ? 'engine-icons/codex.svg'
          : '';

  if (!path) return '';

  try {
    if (typeof chrome !== 'undefined' && chrome?.runtime?.getURL) {
      return chrome.runtime.getURL(path);
    }
  } catch {
    // ignore
  }

  return `/${path}`;
}

// Many websites enforce CSP that blocks `img-src chrome-extension://...` for DOM injected by
// content scripts. Returning a `data:` URL makes the Quick Panel header icon much more likely
// to render across sites.
const engineIconDataUrlCache = new Map<string, string>();

function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  // Chunk to avoid call stack limits
  const chunkSize = 0x8000;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const chunk = bytes.subarray(i, i + chunkSize);
    binary += String.fromCharCode(...chunk);
  }
  return btoa(binary);
}

async function resolveEngineIconUrl(engineName: string): Promise<string> {
  const normalized = engineName.trim();
  if (!normalized) return '';
  const cached = engineIconDataUrlCache.get(normalized);
  if (cached) return cached;

  const extensionUrl = getEngineIconUrl(normalized);
  if (!extensionUrl) return '';

  try {
    const response = await fetch(extensionUrl);
    if (!response.ok) return extensionUrl;

    if (extensionUrl.endsWith('.svg')) {
      const svg = await response.text();
      const dataUrl = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
      engineIconDataUrlCache.set(normalized, dataUrl);
      return dataUrl;
    }

    if (extensionUrl.endsWith('.png')) {
      const buffer = await response.arrayBuffer();
      const base64 = arrayBufferToBase64(buffer);
      const dataUrl = `data:image/png;base64,${base64}`;
      engineIconDataUrlCache.set(normalized, dataUrl);
      return dataUrl;
    }
  } catch {
    // ignore
  }

  return extensionUrl;
}

/** Handle QUICK_PANEL_SET_SESSION_ENGINE message. */
async function handleSetSessionEngine(
  message: QuickPanelSetSessionEngineMessage,
  sender: chrome.runtime.MessageSender,
): Promise<QuickPanelSetSessionEngineResponse> {
  const tabId = sender?.tab?.id;
  if (typeof tabId !== 'number') {
    return { success: false, error: 'Quick Panel request must originate from a tab.' };
  }

  const sessionId = normalizeString(message?.payload?.sessionId).trim();
  const engineNameRaw = message?.payload?.engineName;

  if (!sessionId) return { success: false, error: 'sessionId is required' };
  if (!isValidCliPreference(engineNameRaw)) {
    return { success: false, error: 'Invalid engineName' };
  }

  const stored = await chrome.storage.local.get([STORAGE_KEYS.NATIVE_SERVER_PORT]);
  const port = normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;

  const exists = await validateSession(port, sessionId);
  if (exists) {
    return {
      success: false,
      error: 'Engine is locked for persisted sessions. Start a new Quick Chat to switch engines.',
    };
  }

  quickSessionEngineBySessionId.set(sessionId, engineNameRaw);
  return {
    success: true,
    engineName: engineNameRaw,
    engineDisplayName: toEngineDisplayName(engineNameRaw),
    brandIconUrl: engineNameRaw ? await resolveEngineIconUrl(engineNameRaw) : '',
  };
}

/** Handle QUICK_PANEL_GET_BRANDING message. */
async function handleGetBranding(
  message: QuickPanelGetBrandingMessage,
): Promise<QuickPanelGetBrandingResponse> {
  try {
    const stored = await chrome.storage.local.get([STORAGE_KEYS.NATIVE_SERVER_PORT]);

    const port =
      normalizePort(stored?.[STORAGE_KEYS.NATIVE_SERVER_PORT]) ?? NATIVE_HOST.DEFAULT_PORT;
    const sessionId = normalizeString(message?.payload?.sessionId).trim();

    if (!sessionId) {
      const engineName = QUICK_PANEL_DEFAULT_ENGINE_NAME;
      return {
        success: true,
        engineName,
        engineDisplayName: toEngineDisplayName(engineName),
        brandIconUrl: engineName ? await resolveEngineIconUrl(engineName) : '',
      };
    }

    const exists = await validateSession(port, sessionId);
    if (!exists) {
      const engineName = getQuickSessionEngine(sessionId);
      return {
        success: true,
        engineName,
        engineDisplayName: toEngineDisplayName(engineName),
        brandIconUrl: engineName ? await resolveEngineIconUrl(engineName) : '',
      };
    }

    const url = `http://127.0.0.1:${port}/agent/sessions/${encodeURIComponent(sessionId)}`;
    const response = await fetch(url);
    if (!response.ok) {
      const engineName = QUICK_PANEL_DEFAULT_ENGINE_NAME;
      return {
        success: true,
        engineName,
        engineDisplayName: toEngineDisplayName(engineName),
        brandIconUrl: engineName ? await resolveEngineIconUrl(engineName) : '',
      };
    }

    const payload = (await response.json().catch(() => null)) as any;
    const engineName =
      normalizeString(payload?.session?.engineName).trim() || QUICK_PANEL_DEFAULT_ENGINE_NAME;
    return {
      success: true,
      engineName,
      engineDisplayName: toEngineDisplayName(engineName),
      brandIconUrl: engineName ? await resolveEngineIconUrl(engineName) : '',
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return { success: false, error: msg || 'Failed to resolve branding' };
  }
}

// ============================================================
// Initialization
// ============================================================

/**
 * Initialize the Quick Panel Agent Handler.
 * Sets up message listeners and tab cleanup handlers.
 */
export function initQuickPanelAgentHandler(): void {
  if (initialized) return;
  initialized = true;

  // Track sidepanel presence via a port from the sidepanel UI.
  chrome.runtime.onConnect.addListener((port) => {
    if (port?.name !== 'ruminer_sidepanel_presence') return;

    let tabId: number | null = null;

    port.onMessage.addListener((msg: any) => {
      const nextTabId = typeof msg?.tabId === 'number' ? msg.tabId : null;
      if (typeof nextTabId === 'number' && Number.isFinite(nextTabId)) {
        tabId = nextTabId;
        sidepanelPresenceByTabId.set(nextTabId, { connectedAt: Date.now() });
      }
    });

    port.onDisconnect.addListener(() => {
      if (typeof tabId === 'number') sidepanelPresenceByTabId.delete(tabId);
    });
  });

  // Message listener for Quick Panel messages
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    // Handle QUICK_PANEL_SEND_TO_AI
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_SEND_TO_AI) {
      handleSendToAI(message as QuickPanelSendToAIMessage, sender)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_CANCEL_AI
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_CANCEL_AI) {
      handleCancelAI(message as QuickPanelCancelAIMessage, sender)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_OPEN_SIDEPANEL
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_OPEN_SIDEPANEL) {
      handleOpenSidepanel(message, sender)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_ACTIVATE_SESSION
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_ACTIVATE_SESSION) {
      handleActivateSession(message as QuickPanelActivateSessionMessage, sender)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_OPEN_SESSION
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_OPEN_SESSION) {
      handleOpenSession(message as QuickPanelOpenSessionMessage)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_DELETE_SESSION
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_DELETE_SESSION) {
      handleDeleteSession(message as QuickPanelDeleteSessionMessage)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_PERSIST_SESSION
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_PERSIST_SESSION) {
      handlePersistSession(message as QuickPanelPersistSessionMessage)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_GET_BRANDING
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_GET_BRANDING) {
      handleGetBranding(message as QuickPanelGetBrandingMessage)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    // Handle QUICK_PANEL_SET_SESSION_ENGINE
    if (message?.type === BACKGROUND_MESSAGE_TYPES.QUICK_PANEL_SET_SESSION_ENGINE) {
      handleSetSessionEngine(message as QuickPanelSetSessionEngineMessage, sender)
        .then(sendResponse)
        .catch((err) => {
          const msg = err instanceof Error ? err.message : String(err);
          sendResponse({ success: false, error: msg || 'Unknown error' });
        });
      return true; // Async response
    }

    return false;
  });

  // Clean up requests when their tab is closed
  chrome.tabs.onRemoved.addListener((tabId) => {
    for (const [requestId, request] of activeRequests) {
      if (request.tabId === tabId) {
        cleanupRequest(requestId, 'tab_removed');
      }
    }
  });

  console.debug(`${LOG_PREFIX} Initialized`);
}
